import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "../styles/colors";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },

  header: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerInfo: { flex: 1 },
  headerTitle: { fontSize: 17, fontWeight: "800", color: Colors.white },
  headerSub: { fontSize: 12, color: "rgba(255,255,255,0.5)", marginTop: 1 },
  aiDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.accentGreen,
    borderWidth: 2,
    borderColor: Colors.primary,
    position: "absolute",
    bottom: 0,
    right: 0,
  },
  avatarWrap: { position: "relative" },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },

  petSelector: {
    backgroundColor: Colors.card,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Colors.background,
  },
  petSelectorLabel: { fontSize: 11, fontWeight: "700", color: Colors.textSecondary, letterSpacing: 0.8, marginBottom: 10, textTransform: "uppercase" },
  petChipsRow: { flexDirection: "row", gap: 8 },
  petChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: Colors.background,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  petChipActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + "12",
  },
  petChipText: { fontSize: 13, fontWeight: "600", color: Colors.textSecondary },
  petChipTextActive: { color: Colors.primary, fontWeight: "700" },
  allChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: Colors.background,
    borderWidth: 1.5,
    borderColor: "transparent",
    justifyContent: "center",
  },
  allChipActive: { borderColor: Colors.primary, backgroundColor: Colors.primary + "12" },
  allChipText: { fontSize: 13, fontWeight: "600", color: Colors.textSecondary },
  allChipTextActive: { color: Colors.primary, fontWeight: "700" },

  messagesList: { paddingHorizontal: 16, paddingVertical: 16 },

  msgRow: { marginBottom: 14 },
  msgRowUser: { alignItems: "flex-end" },
  msgRowAi: { alignItems: "flex-start" },

  msgBubbleUser: {
    backgroundColor: Colors.primary,
    borderRadius: 18,
    borderBottomRightRadius: 5,
    paddingHorizontal: 16,
    paddingVertical: 11,
    maxWidth: width * 0.75,
  },
  msgBubbleAi: {
    backgroundColor: Colors.card,
    borderRadius: 18,
    borderBottomLeftRadius: 5,
    paddingHorizontal: 16,
    paddingVertical: 11,
    maxWidth: width * 0.78,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  msgTextUser: { color: Colors.white, fontSize: 14, lineHeight: 20 },
  msgTextAi: { color: Colors.text, fontSize: 14, lineHeight: 22 },
  msgTime: { fontSize: 10, color: Colors.textSecondary, marginTop: 4, paddingHorizontal: 4 },

  aiHeaderRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 6 },
  aiHeaderIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: Colors.primary + "18",
    justifyContent: "center",
    alignItems: "center",
  },
  aiHeaderText: { fontSize: 11, fontWeight: "700", color: Colors.primary, letterSpacing: 0.5 },

  typingBubble: {
    backgroundColor: Colors.card,
    borderRadius: 18,
    borderBottomLeftRadius: 5,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: "row",
    gap: 5,
    alignItems: "center",
    alignSelf: "flex-start",
    marginBottom: 14,
    marginLeft: 16,
  },
  typingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Colors.textSecondary,
    opacity: 0.5,
  },

  quickContainer: {
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  quickLabel: { fontSize: 11, color: Colors.textSecondary, fontWeight: "600", marginBottom: 8, letterSpacing: 0.5 },
  quickRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  quickChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.card,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.background,
  },
  quickChipText: { fontSize: 12, fontWeight: "600", color: Colors.text },

  inputBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.card,
    borderTopWidth: 1,
    borderTopColor: Colors.background,
  },
  inputWrap: {
    flex: 1,
    backgroundColor: Colors.background,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 10,
    maxHeight: 100,
  },
  input: {
    fontSize: 14,
    color: Colors.text,
    lineHeight: 20,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  sendBtnDisabled: {
    backgroundColor: Colors.background,
    shadowOpacity: 0,
    elevation: 0,
  },
});