import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "../styles/colors";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.primary },
  container: { flex: 1, backgroundColor: Colors.primary },
  content: { paddingHorizontal: 24, paddingTop: 16, paddingBottom: 48 },

  orb: {
    position: "absolute",
    width: width * 0.75,
    height: width * 0.75,
    borderRadius: width * 0.375,
    backgroundColor: Colors.secondary,
    top: -width * 0.28,
    right: -width * 0.22,
    opacity: 0.5,
  },
  orbBottom: {
    position: "absolute",
    width: width * 0.45,
    height: width * 0.45,
    borderRadius: width * 0.225,
    backgroundColor: Colors.accentLight,
    bottom: -width * 0.1,
    left: -width * 0.12,
    opacity: 0.06,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 28,
    paddingTop: 8,
  },
  back: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  logoRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  logo: { color: Colors.white, fontSize: 13, fontWeight: "800", letterSpacing: 2 },

  badgeRow: { marginBottom: 14 },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.accentLight,
  },
  badgeText: { color: Colors.accentLight, fontSize: 11, fontWeight: "700", letterSpacing: 1.5 },

  title: {
    fontSize: Math.min(width * 0.1, 40),
    fontWeight: "800",
    color: Colors.white,
    lineHeight: Math.min(width * 0.125, 50),
    marginBottom: 10,
    letterSpacing: -0.5,
  },
  sub: { fontSize: 15, color: "rgba(255,255,255,0.45)", marginBottom: 24, lineHeight: 22 },

  stepIndicator: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  stepItem: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
  stepDot: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  stepDotActive: {
    backgroundColor: Colors.accentLight,
    borderColor: Colors.accentLight,
    shadowColor: Colors.accentLight,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  stepDotDone: { backgroundColor: Colors.accentLight, borderColor: Colors.accentLight },
  stepLabel: { fontSize: 12, color: "rgba(255,255,255,0.3)", fontWeight: "500" },
  stepLabelActive: { color: Colors.white, fontWeight: "700" },
  stepLine: { flex: 1, height: 1.5, backgroundColor: "rgba(255,255,255,0.1)", marginHorizontal: 4 },
  stepLineDone: { backgroundColor: Colors.accentLight },

  formCard: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    marginBottom: 20,
    gap: 6,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.accentLight,
    letterSpacing: 1.5,
    marginBottom: 10,
    textTransform: "uppercase",
  },

  dividerField: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.07)",
    marginVertical: 2,
  },

  passwordHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
  },
  passwordHintText: { fontSize: 12, color: "rgba(255,255,255,0.4)", flex: 1 },

  actions: { gap: 12 },

  btnPrimary: {
    backgroundColor: Colors.accentLight,
    paddingVertical: Math.min(height * 0.022, 18),
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: Colors.accentLight,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  btnPrimaryText: { color: Colors.primary, fontSize: 16, fontWeight: "800", letterSpacing: 0.2 },
  btnArrow: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },

  dividerRow: { flexDirection: "row", alignItems: "center", gap: 12, marginVertical: 2 },
  divider: { flex: 1, height: 1, backgroundColor: "rgba(255,255,255,0.08)" },
  dividerText: { color: "rgba(255,255,255,0.25)", fontSize: 13, fontWeight: "500" },

  btnSecondary: {
    paddingVertical: Math.min(height * 0.02, 16),
    borderRadius: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  btnSecondaryText: { color: "rgba(255,255,255,0.7)", fontSize: 15, fontWeight: "600" },

  legalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
  },
  legalText: { textAlign: "center", fontSize: 11, color: "rgba(255,255,255,0.25)" },
});